const statusApplication = {
  SUCCESS_FULL: 200,
  SUCCESS_CREATED: 201,
  SUCCESS_NO_CONTENT: 204,
  ERROR_BAD_REQUEST: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_NOT_FOUND: 404,
  ERROR_CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
};

module.exports = statusApplication;
